// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBaqI-SvwlR66_KPXz60CYcwavH5SB3qA',
    appId: '1:318113582455:web:88dd0ba05fbb2614756572',
    messagingSenderId: '318113582455',
    projectId: 'nutrichef-406c9',
    authDomain: 'nutrichef-406c9.firebaseapp.com',
    storageBucket: 'nutrichef-406c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI6jvQxCzR7act4CFDzZ5l260Yh01_CyI',
    appId: '1:318113582455:android:383ed6a7b3ce4854756572',
    messagingSenderId: '318113582455',
    projectId: 'nutrichef-406c9',
    storageBucket: 'nutrichef-406c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMDl-28o9ADmrbSwjHmpk_uUfeHeVQhUM',
    appId: '1:318113582455:ios:58fda22e833a57d5756572',
    messagingSenderId: '318113582455',
    projectId: 'nutrichef-406c9',
    storageBucket: 'nutrichef-406c9.firebasestorage.app',
    iosBundleId: 'com.example.nutrichef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMDl-28o9ADmrbSwjHmpk_uUfeHeVQhUM',
    appId: '1:318113582455:ios:58fda22e833a57d5756572',
    messagingSenderId: '318113582455',
    projectId: 'nutrichef-406c9',
    storageBucket: 'nutrichef-406c9.firebasestorage.app',
    iosBundleId: 'com.example.nutrichef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBaqI-SvwlR66_KPXz60CYcwavH5SB3qA',
    appId: '1:318113582455:web:1abb31878bc495a2756572',
    messagingSenderId: '318113582455',
    projectId: 'nutrichef-406c9',
    authDomain: 'nutrichef-406c9.firebaseapp.com',
    storageBucket: 'nutrichef-406c9.firebasestorage.app',
  );
}
